version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ticket-service-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_LOCAL}
      MYSQL_DATABASE: ${MYSQL_DATABASE_LOCAL}
      MYSQL_USER: ${MYSQL_USER_LOCAL}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_LOCAL}

    ports:
      - "3306:3306"

    volumes:
      - ticket-service-data:/var/lib/mysql

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  ticket-service-data:
