version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ticket-service-mysql-test
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_TEST}
      MYSQL_DATABASE: ${MYSQL_DATABASE_TEST}
      MYSQL_USER: ${MYSQL_USER_TEST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_TEST}

    ports:
      - "3307:3306"

    volumes:
      - ticket-service-test-data:/var/lib/mysql

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  ticket-service-test-data:
