version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ticket-service-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_LOCAL}
      MYSQL_DATABASE: ${MYSQL_DATABASE_LOCAL}
      MYSQL_USER: ${MYSQL_USER_LOCAL}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_LOCAL}

    ports:
      - "3306:3306"

    volumes:
      - ticket-service-data:/var/lib/mysql

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.2
    container_name: ticket-service-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ticket-service-redis-data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: ticket-service-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - mysql

  grafana:
    image: grafana/grafana:latest
    container_name: ticket-service-grafana
    ports:
      - "3000:3000"
    volumes:
      - ticket-service-grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  ticket-service-data:
  ticket-service-grafana-data:
  ticket-service-redis-data: